version: "3.4"

services:
  frontend:
    build:
      context: frontend/
    environment:
      VUE_APP_BACKEND_URL: http://localhost:8000
    ports:
      - 8080:80

  backend:
    build:
      context: backend/
    environment:
      SHOPPING_DATABASE_URI: mongodb://mongodb:27017/shopping
    ports:
      - 8000:80
  
  mongodb:
    image: mongo:3
    ports:
      - 27017:27017
